---
# Ansible playbook to update & upgrade the selected hosts

- hosts: gawds
  remote_user: ansiadmin
  become: yes
  become_method: sudo

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes
  - name: Upgrade (full) all packages to the latest version
    apt:
     upgrade: full
  - name: Update (dist) all packages to the latest version
    apt:
     upgrade: dist

